name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [12, 13, 14, 16, 17, 18]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: npm install
      - run: npm install --only=dev
      - run: npm run lint
      - run: npm test
